'use server';

/**
 * @fileOverview An AI agent that generates personalized focus tips.
 *
 * - generateFocusTip - A function that generates personalized focus tips.
 * - GenerateFocusTipInput - The input type for the generateFocusTip function.
 * - GenerateFocusTipOutput - The return type for the generateFocusTip function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateFocusTipInputSchema = z.object({
  userPreferences: z
    .string()
    .describe('The user preferences for focus tips, such as preferred techniques or areas of focus.'),
  pastResponses: z
    .string()
    .describe('The user past responses to focus prompts, to avoid repeat suggestions.'),
});
export type GenerateFocusTipInput = z.infer<typeof GenerateFocusTipInputSchema>;

const GenerateFocusTipOutputSchema = z.object({
  focusTip: z.string().describe('A personalized focus tip generated by AI.'),
});
export type GenerateFocusTipOutput = z.infer<typeof GenerateFocusTipOutputSchema>;

export async function generateFocusTip(input: GenerateFocusTipInput): Promise<GenerateFocusTipOutput> {
  return generateFocusTipFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateFocusTipPrompt',
  input: {schema: GenerateFocusTipInputSchema},
  output: {schema: GenerateFocusTipOutputSchema},
  prompt: `You are a helpful AI assistant that provides personalized focus tips to users.

  Based on the user's preferences and past responses, generate a unique and helpful focus tip.

  User Preferences: {{{userPreferences}}}
  Past Responses: {{{pastResponses}}}

  Focus Tip:`,
});

const generateFocusTipFlow = ai.defineFlow(
  {
    name: 'generateFocusTipFlow',
    inputSchema: GenerateFocusTipInputSchema,
    outputSchema: GenerateFocusTipOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
